### ISSUE TITLE
Missing data in the zip package

### ISSUE THREAD

**Issue by MyGIS** [qgis/QGIS-Training-Data#10]
The compiled training data does not have the training_data.gpkg file in it as per the training material as per page 14,  2.2.2 step#5

**Comment by DelazJ** [comment]
@MyGIS Thanks for reporting. If you have downloaded the data more than a week ago, could you download it again please (the link was leading to an old dataset). Otherwise, if it's recent could you provide the link you use or the page of the download instructions?

**Comment by MyGIS** [comment]
@DelazJ , will do thanks.

**Comment by MyGIS** [comment]
@DelazJ , I downloaded from here:
https://codeload.github.com/qgis/QGIS-Training-Data/zip/QGIS-Training-Data-v1.0 on 29th August 2018

**Comment by DelazJ** [comment]
@MyGIS The v1.0 did not have the data (it adresses 2.18 training manual). You should download the v2 whose link is provided in online docs.
FYI the testing manual (which will become 3.4 docs) is being updated so not all the changes are unfortunately synchronous. A new update is provided every day so if you get something not working, retry with updated data/docs a couple of days later and do not hesitate to report.

Let me know if new download from the current docs fixes the issue for you, please. Thanks

**Comment by MyGIS** [comment]
Thanks @DelazJ .
This issue can be closed.

**Comment by DelazJ** [comment]
Thanks
