### ISSUE TITLE
Incorrect path name

### ISSUE THREAD

**Issue by MyGIS** [qgis/QGIS-Training-Data#11]
Page 13 last paragraph, the shapefile roads.shp should be in folder /epsg4326/

**Comment by DelazJ** [comment]
> Page 13 last paragraph, the shapefile roads.shp

Indexing by lesson number (as you did in the other report) or using the online link to the lesson would be more helpful to us and save us time on finding what you refer to.
That said, I guess you are referring to [lesson 2.2.1](https://docs.qgis.org/testing/en/docs/training_manual/introduction/preparation.html#basic-fa-prepare-a-map) and based on the recent data structure, i'm afraid that I could not find the issue. There's no more `epsg4326` folder in the data.

**Comment by DelazJ** [comment]
Unless I misunderstand the report

**Comment by havatv** [comment]
Perhaps this one could be closed? We can not reproduce it, and there is a lack of feedback.

**Comment by DelazJ** [comment]
Indeed. The main issue is actually addressed in #10.
