### ISSUE TITLE
Shapefile data without .shp file

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Training-Data#2]
Looking at the loaded data, it appears that in https://github.com/qgis/QGIS-Training-Data/tree/master/training_manual_data there are `urban_4326` files with only .prj and .qpj extensions. Is that normal? And any reason to not have this data under a folder (epsg4326 for example) ?

**Comment by ghtmtt** [comment]
Don't know actually.. I think this data where set in the original repo long time ago.. Maybe @timlinux knows something more

**Comment by timlinux** [comment]
Hmm no I don't recall. Feel free to re-organise the data as needed and clean away crufty stuff.

**Comment by DelazJ** [comment]
Looking for `urban_4326` in GitHub search tool it appears that the only place it's mentioned is https://github.com/qgis/QGIS-Documentation/blob/583741bba32fd4879b647e3810bada8d052bdb78/source/docs/training_manual/databases/db_manager.rst#exporting-data-from-a-database-with-db-manager. And it's a file the student might save so not sure it's needed in the repo.
