### ISSUE TITLE
Missing shapefile

### ISSUE THREAD

**Issue by nrtriana** [qgis/QGIS-Training-Data#21]
In QGIS Project. (2019). QGIS Training Manual Release 3.4. Retrieved from https://docs.qgis.org/3.4/pdf/en/QGIS-3.4-QGISTrainingManual-en.pdf there is some references to exercise_data/shapefile/protected_areas.shp file that is missing in QGIS Training Data files.

**Comment by Codym48** [comment]
While the protected_areas.shp file is missing from the `master` branch of the QGIS-Training-Data repository, it is present in the QGIS-Training-Data-2.0.zip archive:

![compare](https://user-images.githubusercontent.com/34431661/80871298-98692c80-8c60-11ea-85ed-f28fac86c055.png)

And this archive is linked from the QGIS 3.4 Training Manual:

![pdflink](https://user-images.githubusercontent.com/34431661/80871304-a9b23900-8c60-11ea-811a-ea4f20b0e22a.png)

Should these files be restored in the `master` branch?

**Comment by Codym48** [comment]
Related to qgis/QGIS-Documentation#4147
