### ISSUE TITLE
QGIS server example projects point to wrong repo

### ISSUE THREAD

**Issue by riccardoklinger** [qgis/QGIS-Training-Data#32]
the qgs file is pointing towards @pcav home folder.     
<layer-tree-layer providerKey="spatialite" name="airports" expanded="1" source="dbname='/home/paolo/Desktop/QGIS-Training-Data/exercise_data/qgis-server-tutorial-data/naturalearth.sqlite' table=&quot;airports&quot; (geom) sql=" id="airports20160924201425088" checked="Qt::Checked">
      <customproperties/>
    </layer-tree-layer>

**Comment by pcav** [comment]
Thanks @riccardoklinger !
