### ISSUE TITLE
more_analysis\Zoning already dissolved

### ISSUE THREAD

**Issue by jveenstra1** [qgis/QGIS-Training-Data#36]
The Generalised_Zoning_Dissolve_UTM33S.shp is already dissolved which makes 8.4.16. Finding rural areas steps 6-14 unnecessary.  Learning the Dissolve tool is useful, so it'd be nice to have the file with multiple polygons to start the exercise with.

**Comment by havatv** [comment]
The training manual has been updated to reflect that dissolving is not necessary. If you think that dissolve is an important algorithm to include in the training manual, please open an issue in QGIS-Documentation.
