### ISSUE TITLE
 Dataset from the Training data repository doesn´t work

### ISSUE THREAD

**Issue by Nromero93** [qgis/QGIS-Training-Data#41]
When I open the archive i've download it is corrupted, i couldn´t unzip it and doesn´t have all the documents needed. I've try several times.

Page URL:
https://docs.qgis.org/3.16/es/docs/training_manual/foreword/intro.html#data

**Comment by DelazJ** [comment]
@Nromero93 I cannot confirm. I tried after you opened https://github.com/qgis/QGIS-Documentation/issues/6598 and it works without any problem. What are the error messages you get and what files are missing? And I do not understand what you mean by  "When I open the archive [...] i couldn't unzip"; you don't need to open before unzipping, do you? Someone reported the same issue few days ago and was told to try with 7-zip. And it worked. Maybe you should also.

**Comment by Nromero93** [comment]
I've dowloaded 7-zip. Unzipped the documents and there is only this 2 documents:
- Forestry
- Example.qgs

But there is no archive with the name "protected_area.shp" as the "2.2 Lesson: Adding your first layers" tell you.

**Comment by DelazJ** [comment]
A local issue, I'm afraid. What is the size of your zip file? Tested right now.
![Peek 17-03-2021 22-13](https://user-images.githubusercontent.com/7983394/111539440-2ca38b80-876e-11eb-8426-d4e7afb99e0b.gif)

**Comment by Nromero93** [comment]
The size is 27.3 MB.

I've tried to download it several times :(

**Comment by DelazJ** [comment]
Mine is 235.6 MB
Not sure it'd change anything but... Go to https://github.com/qgis/QGIS-Training-Data/tree/release_3.16, expand the code button on the right and try "download zip"

**Comment by DelazJ** [comment]
Closing
