### ISSUE TITLE
Where is the roads layer?

### ISSUE THREAD

**Issue by readyready15728** [qgis/QGIS-Training-Data#43]
https://docs.qgis.org/3.16/en/docs/training_manual/answers/answers.html#interface-preparation-1

"Your map should have seven layers:" (among them "roads"). The problem is I don't see where the roads layer is in the training data, except possibly as a GRASS mapset, and as a neophyte reading tutorial material I shouldn't be expected to know how to load data for a different GIS towards the very beginning.

**Comment by DelazJ** [comment]
@readyready15728 have you gone through https://docs.qgis.org/3.16/en/docs/training_manual/basic_map/preparation.html#basic-fa-loading-vector-data-from-a-geopackage-database before trying the exercice at  https://docs.qgis.org/3.16/en/docs/training_manual/basic_map/preparation.html#backlink-vector-load-more-data?

**Comment by readyready15728** [comment]
How embarrassing! Thanks for the feedback.
