### ISSUE TITLE
Dataset from the Training data repository doesn´t work

### ISSUE THREAD

**Issue by Jas977** [qgis/QGIS-Training-Data#44]
When I open the archive i've download it is corrupted, i'v try several time and when i use reparation fonction from Winrar nothing change and in the archives several documents are missing like shapefile. 
 what can i do for fix that please ?

**Comment by gioman** [comment]
> https://github.com/qgis/QGIS-Training-Data/archive/release_3.16.zip

no errors here (7zip).

**Comment by gioman** [comment]
> same trouble :(

it seems you connection has some trouble.
