### ISSUE TITLE
SpaciaLite database landuse.sqlite does not contain landuse layer?

### ISSUE THREAD

**Issue by BenJHunt** [qgis/QGIS-Training-Data#50]
I've tried loading the landuse.sqlite database from the exercise_data files into QGIS 3.22.0, but it suggests "Database does not exist" rather than showing the landuse layer (as per Training Manual para 2.2.4) - screenshot clip attached.
<img width="269" alt="Screenshot 2021-11-03 at 19 29 55" src="https://user-images.githubusercontent.com/34163070/140180383-fe9fd254-51ad-4e50-ab3d-76b33c4265b4.png">

Thanks, Ben

**Comment by DelazJ** [comment]
I think this is a QGIS issue and not a doc one. see https://github.com/qgis/QGIS/issues/45725

**Comment by gioman** [comment]
Closing as duplicate.
