### ISSUE TITLE
error opening landuse.sqlite

### ISSUE THREAD

**Issue by fcarella** [qgis/QGIS-Training-Data#51]
Section 2.2.4 in the [tutorial...](https://docs.qgis.org/3.22/en/docs/training_manual/basic_map/preparation.html#basic-fa-loading-vector-data-from-a-spatialite-database-with-the-browser) doesnt work.  You get a "Database does not exist: landuse.sqlite" error when connecting to the database.  I downloaded "Training data repository" from [here...](https://docs.qgis.org/3.22/en/docs/training_manual/foreword/intro.html#data)

**Comment by gioman** [comment]
@fcarella not an error, but a bug in the latest release of QGIS that is being actively fixes as we speak.
