### ISSUE TITLE
link in Training Manual's Chapter 1.2

### ISSUE THREAD

**Issue by rootsmusic** [qgis/QGIS-Training-Data#54]
In the [last section](https://github.com/qgis/QGIS-Documentation/blob/master/docs/training_manual/foreword/intro.rst#data), should the link for "Training data repository" be changed to https://github.com/qgis/QGIS-Training-Data/tree/release_3.16 ?

**Comment by DelazJ** [comment]
I don't think so. Testing doc points to master zip, and ltr docs point to corresponding release_xxx zip file. And download seems fine here. Can you explain why, please?

**Comment by rootsmusic** [comment]
@DelazJ In QGIS Documentation, [the same page](https://docs.qgis.org/3.16/en/docs/training_manual/foreword/intro.html) actually links to a different path.  Yesterday, I tried to download it but repeatedly failed.  But it downloaded successfully today.
